apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-brukernotifikasjon
  namespace: default
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9029
  liveness:
    path: /pam-brukernotifikasjon/internal/isAlive
    initialDelay: 20
  readiness:
    path: /pam-brukernotifikasjon/internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ servicebruker_brukernotifikasjon }}
        mountPath: /serviceuser/kafka/brukernotifikasjon/
      # TODO husk å fjerne tilgang til denne for appen fra vault
      # - kvPath: {{ servicebruker_cv }}
      #  mountPath: /serviceuser/kafka/cv/
  webproxy: false
  prometheus:
    enabled: true
    path: /pam-brukernotifikasjon/prometheus
  env:
    - name: JDBC_URL
      value: {{ jdbc_url }}
    - name: DB_VAULT_PATH
      value: {{ db_vault_path }}
    - name: DB_VAULT_USERNAME
      value: {{ db_vault_username }}