apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-brukernotifikasjon
  namespace: default
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9029
  liveness:
    path: /pam-brukernotifikasjon/internal/isAlive
    initialDelay: 20
  readiness:
    path: /pam-brukernotifikasjon/internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
  webproxy: false
  prometheus:
    enabled: true
    path: /pam-brukernotifikasjon/prometheus
