apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-brukernotifikasjon
  namespace: teampam
  labels:
    team: teampam
spec:
  accessPolicy:
    outbound:
      rules:
        - application: pam-personoppslag
  image: {{ image }}
  port: 9029
  liveness:
    path: /pam-brukernotifikasjon/internal/isAlive
    initialDelay: 300
    timeout: 1
    failureThreshold: 2
  readiness:
    path: /pam-brukernotifikasjon/internal/isReady
    initialDelay: 300
    timeout: 1
    failureThreshold: 2
  replicas:
    min: 1
    max: 1
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  webproxy: false
  azure:
    application:
      enabled: true
  prometheus:
    enabled: true
    path: /pam-brukernotifikasjon/actuator/prometheus
  envFrom:
    - secret: pam-brukernotifikasjon-secret
  env:
    - name: KAFKA_SCHEMA_REGISTRY
      value: {{ kafka_schema_registry }}
    - name: KAFKA_CONSUMER_TOPIC_CV_ENDRET
      value: {{ kafka_consumer_topic_cv_endret }}
    - name: KAFKA_CONSUMER_TOPIC_OPPFOLGING_STARTET
      value: {{ kafka_consumer_topic_oppfolging_startet }}
    - name: KAFKA_CONSUMER_TOPIC_OPPFOLGING_AVSLUTTET
      value: {{ kafka_consumer_topic_oppfolging_avsluttet }}
    - name: KAFKA_CONSUMER_TOPIC_PDL_ID
      value: {{ kafka_consumer_topic_pdl_id }}
    - name: KAFKA_PRODUCER_TOPIC_NY_OPPGAVE
      value: {{ kafka_producer_topic_ny_oppgave }}
    - name: KAFKA_PRODUCER_TOPIC_DONE
      value: {{ kafka_producer_topic_done }}
    - name: ADMIN_ENABLED
      value: {{ adminEnabled }}
    - name: SECURITY_TOKEN_SERVICE
      value: {{ security_token_service }}
    - name: OUTPUT_MELDING_LINK
      value: {{ linkIMelding }}
    - name: PERSONOPPSLAG_SCOPE
      value: {{ personoppslag_scope }}
    - name: PERSONOPPSLAG_BASE_URL
      value: {{ personoppslag_base_url }}
  ingresses:
    - {{ ingress }}
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        tier: {{ cloudsql_db_tier }}
        diskAutoresize: true
        diskType: SSD
        highAvailability: true
        databases:
          - name: pam-brukernotifikasjon
            envVarPrefix: DB