apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-brukernotifikasjon
  namespace: teampam
  labels:
    team: teampam
spec:
  accessPolicy:
    outbound:
      rules:
        - application: pam-personoppslag
    inbound:
      rules:
        - application: pam-brukernotifikasjoner-datastory
  image: {{ image }}
  port: 9029
  liveness:
    path: /pam-brukernotifikasjon/internal/isAlive
    initialDelay: 60
    timeout: 1
    failureThreshold: 2
  readiness:
    path: /pam-brukernotifikasjon/internal/isReady
    initialDelay: 60
    timeout: 1
    failureThreshold: 2
  replicas:
    min: 1
    max: 1
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  webproxy: false
  azure:
    application:
      enabled: true
  prometheus:
    enabled: true
    path: /pam-brukernotifikasjon/actuator/prometheus
  envFrom:
    - secret: pam-brukernotifikasjon-secret
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: KAFKA_SCHEMA_REGISTRY_ONPREM
      value: {{ kafka_schema_registry }}
    - name: KAFKA_SECURITY_PROTOCOL
      value: {{ kafka_security_protocol }}
    - name: KAFKA_CONSUMER_TOPIC_CV_ENDRET
      value: {{ kafka_consumer_topic_cv_endret }}
    - name: KAFKA_CONSUMER_TOPIC_OPPFOLGINGSTATUS
      value: {{ kafka_consumer_topic_oppfolgingstatus }}
    - name: KAFKA_PRODUCER_TOPIC_OPPGAVE
      value: {{ kafka_producer_topic_oppgave }}
    - name: KAFKA_PRODUCER_TOPIC_DONE
      value: {{ kafka_producer_topic_done }}
    - name: ADMIN_ENABLED
      value: {{ adminEnabled }}
    - name: SECURITY_TOKEN_SERVICE
      value: {{ security_token_service }}
    - name: OUTPUT_MELDING_LINK
      value: {{ linkIMelding }}
    - name: PERSONOPPSLAG_SCOPE
      value: {{ personoppslag_scope }}
    - name: PERSONOPPSLAG_BASE_URL
      value: {{ personoppslag_base_url }}
  ingresses:
    - {{ ingress }}
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        tier: {{ cloudsql_db_tier }}
        diskAutoresize: true
        diskType: SSD
        highAvailability: true
        databases:
          - name: pam-brukernotifikasjon
            envVarPrefix: DB
