#kafka:
#  schema:
#    registry:
#      url: http://mock:8081/
datasources:
  default:
    url: 'jdbc:h2:mem:pam-brukernotifikasjon;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations
      initSql:
        - ''
      connection-init-sqls:
        - 'SET ROLE "pam-brukernotifikasjon-admin"'

data.
