server:
  port: 9029
  servlet:
    context-path: /pam-brukernotifikasjon

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web.exposure.include: prometheus

spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:pam-brukernotifikasjon}
    username: ${DB_USERNAME:pam-brukernotifikasjon}
    password: ${DB_PASSWORD:pam-brukernotifikasjon}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      pool-name: default
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - "classpath:databasemigrations"
    initSql:
      - 'SET ROLE "pam-brukernotifikasjon-admin"'

kafka:
  bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  sasl:
    jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_SERVICE_USER:dummy} password=${KAFKA_SERVICE_PASSWORD:ymmud};'
  ssl.truststore.location: ${NAV_TRUSTSTORE_PATH:}
  ssl.truststore.password: ${NAV_TRUSTSTORE_PASSWORD:}
  schema.registry.url: https://${KAFKA_SCHEMA_REGISTRY:localhost:8081}
  topics:
    consumers:
      cv_endret: ${KAFKA_CONSUMER_TOPIC_CV_ENDRET:arbeid-pam-cv-endret-v4-q0}
      oppfolging_startet: ${KAFKA_CONSUMER_TOPIC_OPPFOLGING_STARTET:aapen-arbeidsrettetOppfolging-oppfolgingStartet-v1-p}
      oppfolging_avsluttet: ${KAFKA_CONSUMER_TOPIC_OPPFOLGING_AVSLUTTET:aapen-arbeidsrettetOppfolging-oppfolgingAvsluttet-v1-p}
      pdl_id: ${KAFKA_CONSUMER_TOPIC_PDL_ID:privat-person-pdl-aktor-v1}
    producers:
      ny_oppgave: ${KAFKA_PRODUCER_TOPIC_NY_OPPGAVE:aapen-brukernotifikasjon-nyOppgave-v1}
      done: ${KAFKA_PRODUCER_TOPIC_DONE:aapen-brukernotifikasjon-done-v1}


admin:
  enabled: ${ADMIN_ENABLED:`disabled`}

output.melding.link: ${OUTPUT_MELDING_LINK:`https://arbeidsplassen.nav.no/cv`}
