server:
  port: 9029
  servlet:
    context-path: /pam-brukernotifikasjon

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web.exposure.include: prometheus

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - "classpath:databasemigrations"
    initSql:
      - 'SET ROLE "pam-brukernotifikasjon-admin"'

micronaut:
  application:
    name: brukernotifikasjon


db:
  vault:
    path: ${DB_VAULT_PATH:`postgresql/preprod`}
    username: ${DB_VAULT_USERNAME:`pam-brukernotifikasjon-admin`}

datasources:
  default:
    jdbcUrl: ${JDBC_URL:`jdbc:postgresql://localhost:5432/pam-brukernotifikasjon`}


kafka:
  bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  sasl:
    jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_SERVICE_USER:dummy} password=${KAFKA_SERVICE_PASSWORD:ymmud};'
  ssl.truststore.location: ${NAV_TRUSTSTORE_PATH:}
  ssl.truststore.password: ${NAV_TRUSTSTORE_PASSWORD:}
  schema.registry.url: http://kafka-schema-registry.tpa:8081

  producers:
    default:
      key:
        serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value:
        serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  consumers:
    pam-brukernotifikasjon-cv-v4:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      specific:
        avro:
          reader: false
    pam-brukernotifikasjon-oppfolging-v1:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
    pam-brukernotifikasjon-person-v1:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      specific:
        avro:
          reader: false
  topics:
    consumers:
      cv_endret: ${KAFKA_CONSUMER_TOPIC_CV_ENDRET:`arbeid-pam-cv-endret-v4-q0`}
      oppfolging_startet: ${KAFKA_CONSUMER_TOPIC_OPPFOLGING_STARTET:`no-default`}
      oppfolging_avsluttet: ${KAFKA_CONSUMER_TOPIC_OPPFOLGING_AVSLUTTET:`no-default`}
      pdl_id: ${KAFKA_CONSUMER_TOPIC_PDL_ID:`privat-person-pdl-aktor-v1`}
    producers:
      ny_oppgave: ${KAFKA_PRODUCER_TOPIC_NY_OPPGAVE:`aapen-brukernotifikasjon-nyOppgave-v1`}
      done: ${KAFKA_PRODUCER_TOPIC_DONE:`aapen-brukernotifikasjon-done-v1`}
  health:
    enabled: false


admin:
  enabled: ${ADMIN_ENABLED:`disabled`}



output.melding.link: ${OUTPUT_MELDING_LINK:`https://arbeidsplassen.nav.no/cv`}
