server:
  port: 9029
  servlet:
    context-path: /pam-brukernotifikasjon

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web.exposure.include: prometheus

no.nav.security.jwt:
  client:
    registration:
      personoppslag:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID:dummy}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${PERSONOPPSLAG_SCOPE:some_scope}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID:dummy}
          client-secret: ${AZURE_APP_CLIENT_SECRET:dummy}
          client-auth-method: client_secret_basic


spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:pam-brukernotifikasjon}
    username: ${DB_USERNAME:pam-brukernotifikasjon}
    password: ${DB_PASSWORD:pam-brukernotifikasjon}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      pool-name: default
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - "classpath:databasemigrations"
    initSql:
      - 'SET ROLE "pam-brukernotifikasjon-admin"'

kafka:
  aiven:
    producers:
      topics:
        oppgave: ${KAFKA_PRODUCER_TOPIC_OPPGAVE:aapen-brukernotifikasjon-nyOppgave-v1}
        done: ${KAFKA_PRODUCER_TOPIC_DONE:aapen-brukernotifikasjon-done-v1}
    consumers:
      topics:
        cv_endret: ${KAFKA_CONSUMER_TOPIC_CV_ENDRET:arbeid-pam-cv-endret-v4-q0}
    brokers: ${KAFKA_BROKERS:localhost:9092}
    securityProtocol: SSL
    keystorePath: ${KAFKA_KEYSTORE_PATH:}
    truststorePath: ${KAFKA_TRUSTSTORE_PATH:}
    credstorePassword: ${KAFKA_CREDSTORE_PASSWORD:pwd}
    schemaRegistry: ${KAFKA_SCHEMA_REGISTRY:pwd}
    schemaUsername: ${KAFKA_SCHEMA_REGISTRY_USER:none}
    schemaPassword: ${KAFKA_SCHEMA_REGISTRY_PASSWORD:none}
  properties:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    schema:
      registry:
        url: https://${KAFKA_SCHEMA_REGISTRY_ONPREM:http://localhost:8081}
  consumers:
    topics:
      oppfolging_startet: ${KAFKA_CONSUMER_TOPIC_OPPFOLGING_STARTET:aapen-arbeidsrettetOppfolging-oppfolgingStartet-v1-p}
      oppfolging_avsluttet: ${KAFKA_CONSUMER_TOPIC_OPPFOLGING_AVSLUTTET:aapen-arbeidsrettetOppfolging-oppfolgingAvsluttet-v1-p}
      pdl_id: ${KAFKA_CONSUMER_TOPIC_PDL_ID:privat-person-pdl-aktor-v1}

  ssl:
    truststore:
      location: ${NAV_TRUSTSTORE_PATH:}
      password: ${NAV_TRUSTSTORE_PASSWORD:}
  sasl:
    jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_SERVICE_USER:dummy} password=${KAFKA_SERVICE_PASSWORD:ymmud};'
  consumer.concurrency: 1
  retry.max: 5760
  retry.multiplier: 1.2
  retry.initial_interval: 2000
  retry.max_interval: 30000


admin:
  enabled: ${ADMIN_ENABLED:`disabled`}

metrics.key.conversion_rate: ${METRIC_CONVERSIONRATE:noset}

output.melding.link: ${OUTPUT_MELDING_LINK:https://arbeidsplassen.nav.no/cv}

base.url.personoppslag: ${PERSONOPPSLAG_BASE_URL:http://dummyurl}
