kafka:
  bootstrap:
    servers: localhost:9092
  ssl:
    truststore:
      location: ''
      password: ''
  sasl:
    mechanism: PLAIN
    jaas:
      config: ''
  security:
    protocol: PLAINTEXT
  schema:
    registry:
      url: http://mock:8081/
datasources:
  default:
    url: 'jdbc:h2:mem:flywayDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
io:
  micronaut:
    context:
      condition: true
jpa:
  default:
    packages-to-scan:
      - 'no.nav.cv.repository'
      - 'no.nav.cv.person'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true