CREATE SEQUENCE STATUS_SEQ;

CREATE TABLE STATUS(
    ID                   NUMERIC(19, 0) NOT NULL PRIMARY KEY ,
    UUID                 VARCHAR(36) NOT NULL,
    FOEDSELSNUMMER       VARCHAR(11) NOT NULL,
    STATUS               VARCHAR(50) NOT NULL,
    TIDSPUNKT            TIMESTAMP
);

CREATE INDEX IX_STATUS_TIDSPUNKT
    ON STATUS (FOEDSELSNUMMER, TIDSPUNKT);
