CREATE SEQUENCE STATUS_SEQ;

CREATE TABLE STATUS(
    ID                   NUMERIC(19, 0) NOT NULL PRIMARY KEY ,
    UUID                 VARCHAR(36) NOT NULL,
    AKTOR_ID             VARCHAR(20) NOT NULL,
    FOEDSELSNUMMER       VARCHAR(11) NOT NULL,
    STATUS               VARCHAR(50) NOT NULL,
    TIDSPUNKT            TIMESTAMP,
    FORTSETT_TIDSPUNKT   TIMESTAMP
);

CREATE INDEX IX_STATUS_TIDSPUNKT
    ON STATUS (FOEDSELSNUMMER, TIDSPUNKT);


CREATE SEQUENCE PERSON_IDENT_SEQ;
CREATE TABLE PERSON_IDENT(
    ID                   NUMERIC(19, 0) NOT NULL PRIMARY KEY,
    PERSON_ID_GROUP_ID   CHAR(36) DEFAULT '' NOT NULL,
    PERSON_ID            VARCHAR(11) NOT NULL,
    PERSON_ID_TYPE       VARCHAR(36) NOT NULL,
    GJELDENDE            BOOLEAN NOT NULL
);

